# -*- coding: utf-8 -*-
"""data_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5S5eDPbrGZF3y9Ye9nyB6_BYKqAwwpO
"""

import pandas as pd
from fairlearn.datasets import fetch_adult

def load_and_clean_data():
    # Fetch the Adult Census dataset
    data = fetch_adult(as_frame=True)
    X = data.data
    y = (data.target == ">50K").astype(int)

    # We use 'sex' as the sensitive feature
    sensitive_feature = X['sex']

    # Simple preprocessing: Convert categories to codes for the model
    X_encoded = pd.get_dummies(X)

    return X_encoded, y, sensitive_feature