# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5S5eDPbrGZF3y9Ye9nyB6_BYKqAwwpO
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from fairlearn.reductions import ExponentiatedGradient, DemographicParity
from data_loader import load_and_clean_data
from evaluation import get_fairness_metrics

# 1. Setup Data
X, y, sensitive = load_and_clean_data()
X_train, X_test, y_train, y_test, sens_train, sens_test = train_test_split(
    X, y, sensitive, test_size=0.3, random_state=42
)

# 2. Train Unfair Model
model_raw = RandomForestClassifier(n_estimators=10, random_state=42)
model_raw.fit(X_train, y_train)
y_pred_raw = model_raw.predict(X_test)

# 3. Train Fair Model (Mitigation)
mitigator = ExponentiatedGradient(
    RandomForestClassifier(n_estimators=10, random_state=42),
    constraints=DemographicParity()
)
mitigator.fit(X_train, y_train, sensitive_features=sens_train)
y_pred_fair = mitigator.predict(X_test)

# 4. Compare
print("--- UNFAIR MODEL ---")
print(get_fairness_metrics(y_test, y_pred_raw, sens_test).by_group)

print("\n--- FAIR MODEL ---")
print(get_fairness_metrics(y_test, y_pred_fair, sens_test).by_group)